### ISSUE TITLE
Error after Python 3.10.1 update

### ISSUE THREAD

**Issue by terbin** [rebane2001/mapdat2png#1]
Since updating to `Python 3.10.1` on Windows 11 and installing the modules:
`Pillow-8.4.0-cp310-cp310-win_amd64`
`nbtlib-2.0.4-py3-none-any`
I get the error:

_Traceback (most recent call last):
  File "mapdat2png.py", line 40, in <module>
    datToPng(args.infile,args.outfile)
  File "mapdat2png.py", line 30, in datToPng
    color_id = nbt_file[""]["data"]["colors"][w+h*128]
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\nbtlib\tag.py", line 1167, in __getitem__
    return super().__getitem__(key)
KeyError: ''_

Do you have an idea what could cause this?

Best regards

**Comment by rebane2001** [comment]
Fixed in 893b9db0c834f2481d0106ed54e4b6e456866c27
