### ISSUE TITLE
Unable to create png from map_<id>.dat DataVersion 3463

### ISSUE THREAD

**Issue by terbin** [rebane2001/mapdat2png#3]
Hi Rebane,

When trying to create a .png file from the attached map_536.dat I receive this error:
[map_536.zip](https://github.com/user-attachments/files/16570305/map_536.zip)

```
Traceback (most recent call last):
  File "mapdat2png.py", line 40, in <module>
    datToPng(args.infile,args.outfile)
  File "mapdat2png.py", line 31, in datToPng
    pix[(w,h)] = getColor(color_id)
  File "mapdat2png.py", line 13, in getColor
    color_base_int = mapColors[color_base_id]
IndexError: list index out of range
```

any chance you can fix this for me?

**Comment by terbin** [comment]
Python 3.10.6

nbtlib 2.0.1
Pillow 10.4.0
numpy 1.26.2

**Comment by terbin** [comment]
created a pull request https://github.com/rebane2001/mapdat2png/pull/4
